/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package banking.system;

import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Amit's
 */
public class AccountToAccount extends javax.swing.JPanel {

    Connection con;

    /**
     * Creates new form NewJPanel
     */
    public AccountToAccount() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelAccno = new javax.swing.JLabel();
        labelaccsec = new javax.swing.JLabel();
        labelamount = new javax.swing.JLabel();
        submitTransaction = new javax.swing.JButton();
        firstAcc = new javax.swing.JTextField();
        secAcc = new javax.swing.JTextField();
        amountTrans = new javax.swing.JTextField();
        head = new javax.swing.JLabel();
        clear = new javax.swing.JButton();

        labelAccno.setText("From Account No.");

        labelaccsec.setText("To Account No.");

        labelamount.setText("Enter Amount");

        submitTransaction.setText("Submit");
        submitTransaction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitTransactionActionPerformed(evt);
            }
        });

        head.setBackground(new java.awt.Color(0, 0, 0));
        head.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        head.setForeground(new java.awt.Color(255, 255, 255));
        head.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        head.setText("Account To Account Transaction");
        head.setOpaque(true);

        clear.setText("Clear");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(head, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelamount)
                            .addComponent(labelaccsec)
                            .addComponent(labelAccno))
                        .addGap(78, 78, 78)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(firstAcc)
                            .addComponent(secAcc)
                            .addComponent(amountTrans, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(submitTransaction)
                        .addGap(40, 40, 40)
                        .addComponent(clear)))
                .addContainerGap(66, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {labelAccno, labelaccsec, labelamount});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(head, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelAccno, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(firstAcc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelaccsec)
                    .addComponent(secAcc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelamount)
                    .addComponent(amountTrans, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(submitTransaction)
                    .addComponent(clear))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {labelAccno, labelaccsec, labelamount});

    }// </editor-fold>//GEN-END:initComponents

    private void submitTransactionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitTransactionActionPerformed

        if (!firstAcc.getText().isEmpty() && !secAcc.getText().isEmpty() && !amountTrans.getText().isEmpty()) {
            int accountFirst = Integer.parseInt(firstAcc.getText());
            int accountSec = Integer.parseInt(secAcc.getText());
            int amountrs = Integer.parseInt(amountTrans.getText());
            try {
                con = sqlconnect.getConnection();
                String sql = "UPDATE bank_balance SET balancedb= balancedb-" + amountrs + " WHERE accountno=" + accountFirst;
                System.out.println(sql);

                String sql2 = "UPDATE bank_balance SET balancedb= balancedb+" + amountrs + " WHERE accountno=" + accountSec;
                Statement stat1 = con.createStatement();
                con.setAutoCommit(false);
                int status1 = stat1.executeUpdate(sql);
                int status2 = stat1.executeUpdate(sql2);
                if (status1 != -1 && status2 != -1) {
                    con.commit();
                    JOptionPane.showMessageDialog(BankingSystem.view.firstview, "Transaction is sucessful.", "Transaction Succesful", JOptionPane.INFORMATION_MESSAGE);
                    firstAcc.setText("");
                    secAcc.setText("");
                    amountTrans.setText("");

                } else {
                    con.rollback();
                    JOptionPane.showMessageDialog(BankingSystem.view.firstview, "Request not Completed, Rolling Back", "Transaction Error", JOptionPane.ERROR_MESSAGE);

                }
            } catch (SQLException e) {
               
                JOptionPane.showMessageDialog(BankingSystem.view.firstview, "Something wrong with Databases", "Database Error", JOptionPane.ERROR_MESSAGE);

            } finally {
                sqlconnect.closeConnection();

            }
    }//GEN-LAST:event_submitTransactionActionPerformed

          else {
            JOptionPane.showMessageDialog(BankingSystem.view.firstview, "Please fill in all Fields", "Field Empty", JOptionPane.ERROR_MESSAGE);

        }
    }
    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        firstAcc.setText("");
        secAcc.setText("");
        amountTrans.setText("");

    }//GEN-LAST:event_clearActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField amountTrans;
    private javax.swing.JButton clear;
    private javax.swing.JTextField firstAcc;
    private javax.swing.JLabel head;
    private javax.swing.JLabel labelAccno;
    private javax.swing.JLabel labelaccsec;
    private javax.swing.JLabel labelamount;
    private javax.swing.JTextField secAcc;
    private javax.swing.JButton submitTransaction;
    // End of variables declaration//GEN-END:variables
}
