/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package banking.system;

import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.sql.*;

import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Amit's
 */
public class Accountdetail extends javax.swing.JPanel {

    Connection con;

    public Accountdetail() {
        initComponents();
        details.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        head = new javax.swing.JLabel();
        accnolbl = new javax.swing.JLabel();
        accno = new javax.swing.JTextField();
        details = new javax.swing.JPanel();
        showacc = new javax.swing.JLabel();
        showaccname = new javax.swing.JLabel();
        showaccblnc = new javax.swing.JLabel();
        showdob = new javax.swing.JLabel();
        showadd = new javax.swing.JLabel();
        showmar = new javax.swing.JLabel();
        showemail = new javax.swing.JLabel();
        showsex = new javax.swing.JLabel();
        accountno = new javax.swing.JLabel();
        accountname = new javax.swing.JLabel();
        accountblnc = new javax.swing.JLabel();
        accountdob = new javax.swing.JLabel();
        accountaddr = new javax.swing.JLabel();
        accountmarital = new javax.swing.JLabel();
        accountemail = new javax.swing.JLabel();
        accountsex = new javax.swing.JLabel();
        imgload = new javax.swing.JLabel();
        submit = new javax.swing.JButton();
        clearacc = new javax.swing.JButton();

        head.setBackground(new java.awt.Color(0, 0, 0));
        head.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        head.setForeground(new java.awt.Color(255, 255, 255));
        head.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        head.setText("Account Details");
        head.setOpaque(true);

        accnolbl.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        accnolbl.setText("Account No.:");

        showacc.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        showacc.setText("Account No.");

        showaccname.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        showaccname.setText("Account Holder Name:");

        showaccblnc.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        showaccblnc.setText("Balance:");

        showdob.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        showdob.setText("DOB:");

        showadd.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        showadd.setText("Address");

        showmar.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        showmar.setText("Marital Status:");

        showemail.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        showemail.setText("Email id:");

        showsex.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        showsex.setText("Sex:");

        accountno.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N

        accountname.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N

        accountblnc.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N

        accountdob.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N

        accountaddr.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N

        accountmarital.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N

        accountemail.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N

        accountsex.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N

        imgload.setOpaque(true);

        javax.swing.GroupLayout detailsLayout = new javax.swing.GroupLayout(details);
        details.setLayout(detailsLayout);
        detailsLayout.setHorizontalGroup(
            detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(detailsLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(showacc, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(showaccname)
                    .addComponent(showaccblnc)
                    .addComponent(showdob)
                    .addComponent(showadd)
                    .addComponent(showmar)
                    .addComponent(showemail)
                    .addComponent(showsex))
                .addGap(78, 78, 78)
                .addGroup(detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(detailsLayout.createSequentialGroup()
                        .addGroup(detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(accountno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(detailsLayout.createSequentialGroup()
                                .addGroup(detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(accountsex, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(accountemail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(accountmarital, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(accountdob, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(accountblnc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(accountname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(152, 152, 152)))
                        .addGap(35, 35, 35)
                        .addComponent(imgload, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(detailsLayout.createSequentialGroup()
                        .addComponent(accountaddr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(314, 314, 314))))
        );
        detailsLayout.setVerticalGroup(
            detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(detailsLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(imgload, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(detailsLayout.createSequentialGroup()
                        .addGroup(detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(showacc, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                            .addComponent(accountno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(showaccname)
                            .addComponent(accountname))
                        .addGap(18, 18, 18)
                        .addGroup(detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(showaccblnc)
                            .addComponent(accountblnc))
                        .addGap(18, 18, 18)
                        .addGroup(detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(showdob)
                            .addComponent(accountdob))
                        .addGap(30, 30, 30)
                        .addGroup(detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(showadd)
                            .addComponent(accountaddr, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(showmar)
                            .addComponent(accountmarital))
                        .addGap(18, 18, 18)
                        .addGroup(detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(showemail)
                            .addComponent(accountemail))
                        .addGap(28, 28, 28)
                        .addGroup(detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(showsex)
                            .addComponent(accountsex))))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        detailsLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {showacc, showaccblnc, showaccname, showadd, showdob, showemail, showmar, showsex});

        detailsLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {accountaddr, accountblnc, accountdob, accountemail, accountmarital, accountname, accountno, accountsex});

        submit.setText("Get Details");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });

        clearacc.setText("Clear");
        clearacc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearaccActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(head, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(accnolbl, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(76, 76, 76)
                        .addComponent(accno, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(submit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(clearacc))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(details, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(head, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(accnolbl, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(accno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(submit)
                    .addComponent(clearacc))
                .addGap(18, 18, 18)
                .addComponent(details, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed

        if (!accno.getText().isEmpty()) {
            int accNo = Integer.parseInt(accno.getText().trim());
            try {
                con= sqlconnect.getConnection();
                String sql= "SELECT p.balancedb, a.* FROM bank_balance AS p JOIN accounts AS a ON p.accountno= a.accountnumber WHERE a.accountnumber =" +accNo; 
                
                Statement stat= con.createStatement();
                ResultSet rs= stat.executeQuery(sql);
                if(rs.last()){
                    accountno.setText(rs.getString("accountnumber"));
                    accountname.setText(rs.getString("accountname"));
                    accountblnc.setText(rs.getString("balancedb"));
                    accountdob.setText(rs.getString("accountdob"));
                    accountaddr.setText(rs.getString("accountaddress"));
                    accountsex.setText(rs.getString("accountsex"));
                    accountmarital.setText(rs.getString("accountmarital"));
                    accountemail.setText(rs.getString("accountemail"));
                    details.setVisible(true);
                    try {
                        BufferedImage img= ImageIO.read(getClass().getResourceAsStream(rs.getString("accountimage")));
                        Image img2= img.getScaledInstance(150, 150, Image.SCALE_AREA_AVERAGING);
                        ImageIcon ic= new ImageIcon(img2);
                        imgload.setIcon(ic);
                    } catch (Exception ex) {
                        JOptionPane.showMessageDialog(BankingSystem.view.firstview, "Unable to find image directory", "Directory not found", JOptionPane.ERROR_MESSAGE);
                    }
                    
                
                }
                else{
                JOptionPane.showMessageDialog(BankingSystem.view.firstview, "Account not Exist", "Account not found", JOptionPane.ERROR_MESSAGE);
                }
            } catch (SQLException e) {

                JOptionPane.showMessageDialog(BankingSystem.view.firstview, "Something wrong with Databases", "Database Error", JOptionPane.ERROR_MESSAGE);
            } finally {
                sqlconnect.closeConnection();

            }

        } else {
            JOptionPane.showMessageDialog(BankingSystem.view.firstview, "Please fill in all Fields", "Field Empty", JOptionPane.ERROR_MESSAGE);

        }
    }//GEN-LAST:event_submitActionPerformed

    private void clearaccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearaccActionPerformed
        details.setVisible(false);
    }//GEN-LAST:event_clearaccActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField accno;
    private javax.swing.JLabel accnolbl;
    private javax.swing.JLabel accountaddr;
    private javax.swing.JLabel accountblnc;
    private javax.swing.JLabel accountdob;
    private javax.swing.JLabel accountemail;
    private javax.swing.JLabel accountmarital;
    private javax.swing.JLabel accountname;
    private javax.swing.JLabel accountno;
    private javax.swing.JLabel accountsex;
    private javax.swing.JButton clearacc;
    private javax.swing.JPanel details;
    private javax.swing.JLabel head;
    private javax.swing.JLabel imgload;
    private javax.swing.JLabel showacc;
    private javax.swing.JLabel showaccblnc;
    private javax.swing.JLabel showaccname;
    private javax.swing.JLabel showadd;
    private javax.swing.JLabel showdob;
    private javax.swing.JLabel showemail;
    private javax.swing.JLabel showmar;
    private javax.swing.JLabel showsex;
    private javax.swing.JButton submit;
    // End of variables declaration//GEN-END:variables
}
