/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package banking.system;

import java.sql.*;

/**
 *
 * @author Crusadersplanet
 */
public class checkBalanceView extends javax.swing.JPanel {

    

    /**
     * Creates new form checkBalanceView
     */
    public checkBalanceView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        accnoLabel = new javax.swing.JLabel();
        accNoBalance = new javax.swing.JTextField();
        submitAccNoBalance = new javax.swing.JButton();
        clearBalance = new javax.swing.JButton();
        showBalance = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(600, 180));

        accnoLabel.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        accnoLabel.setText("Enter Account Number:");

        submitAccNoBalance.setText("Submit");
        submitAccNoBalance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitAccNoBalanceActionPerformed(evt);
            }
        });

        clearBalance.setText("Clear");
        clearBalance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBalanceActionPerformed(evt);
            }
        });

        showBalance.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(accnoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(accNoBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(submitAccNoBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(clearBalance))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(showBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 538, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(accnoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(accNoBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(submitAccNoBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clearBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(showBalance, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void submitAccNoBalanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitAccNoBalanceActionPerformed

        Connection con= sqlconnect.getConnection();
        String accountnum= accNoBalance.getText();
        if (con != null) {
            try {
                String sqlstat= "SELECT balancedb FROM bank_balance WHERE accountno=?";
                PreparedStatement ps= con.prepareStatement(sqlstat);
                
                ps.setString(1, accountnum);
                ResultSet rs= ps.executeQuery();
                
                if(rs.last())
                {
                    
                    String availbal= rs.getString("balancedb");
                    showBalance.setText("<html><label>Available Balance in Account No. "+ accountnum+ " is </label><label style=\"color:red\">INR "+ availbal +"</label>" );
                    
                
                }
                

            } catch (SQLException e) {
                e.printStackTrace();

            } finally {
                sqlconnect.closeConnection();
            }

        }
    }//GEN-LAST:event_submitAccNoBalanceActionPerformed

    private void clearBalanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBalanceActionPerformed
        accNoBalance.setText(" ");
        showBalance.setText(" ");
    }//GEN-LAST:event_clearBalanceActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField accNoBalance;
    private javax.swing.JLabel accnoLabel;
    private javax.swing.JButton clearBalance;
    private javax.swing.JLabel showBalance;
    private javax.swing.JButton submitAccNoBalance;
    // End of variables declaration//GEN-END:variables
}
