/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package banking.system;

import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Amit's
 */
public class DeleteAccount extends javax.swing.JPanel {

    Connection con;

    /**
     * Creates new form DeleteAccount
     */
    public DeleteAccount() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headingText = new javax.swing.JLabel();
        accnolabel = new javax.swing.JLabel();
        accno = new javax.swing.JTextField();
        delete = new javax.swing.JButton();

        headingText.setBackground(new java.awt.Color(0, 0, 0));
        headingText.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        headingText.setForeground(new java.awt.Color(255, 255, 255));
        headingText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        headingText.setText("Delete Account");
        headingText.setOpaque(true);

        accnolabel.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        accnolabel.setText("Delete  Account No.");

        delete.setText("Delete");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(headingText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(accnolabel, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(66, 66, 66)
                        .addComponent(accno, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(173, 173, 173)
                        .addComponent(delete)))
                .addContainerGap(73, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(headingText, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(accnolabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(accno, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(delete)
                .addGap(0, 56, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed

        if (!accno.getText().isEmpty()) {
            String accNo = accno.getText();
            int x = JOptionPane.showConfirmDialog(BankingSystem.view.firstview, "Confirm Deletion", "Confirm", JOptionPane.YES_NO_OPTION);

            if (x == 0) {
                try {
                    con = sqlconnect.getConnection();
                    String sql = "DELETE FROM accounts WHERE accountnumber=" + accNo;
                    String sql2 = "DELETE FROM bank_balance WHERE accountno=" + accNo;
                    Statement stat = con.createStatement();
                    int status1 = stat.executeUpdate(sql);
                    int status2 = stat.executeUpdate(sql2);
                    if (status1 != -1 && status2 != -1) {
                        JOptionPane.showMessageDialog(BankingSystem.view.firstview, "Delete sucessful.", "Deleted", JOptionPane.INFORMATION_MESSAGE);
                        accno.setText(" ");

                    }

                } catch (SQLException e) {
                    JOptionPane.showMessageDialog(BankingSystem.view.firstview, "Something wrong with Databases", "Database Error", JOptionPane.ERROR_MESSAGE);
                } finally {
                    sqlconnect.closeConnection();

                }

            } else {
                accno.setText(" ");
            }

        } else {
            JOptionPane.showMessageDialog(BankingSystem.view.firstview, "Please fill in all Fields", "Field Empty", JOptionPane.ERROR_MESSAGE);

        }
    }//GEN-LAST:event_deleteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField accno;
    private javax.swing.JLabel accnolabel;
    private javax.swing.JButton delete;
    private javax.swing.JLabel headingText;
    // End of variables declaration//GEN-END:variables
}
